config/routes.rb
Rails.application.routes.draw do
  resources :sells
  resources :books
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
   root "dashboard#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true

  has_many :sells, dependent: :destroy

  after_create_commit :create_chart

  private 
  def create_chart
    broadcast_append_to(
      'books_charts_channel', 
      partial: '/dashboard/charts/books/chart', 
      locals: { book: self }, 
      target: 'books_charts')
  end

end

app/models/sell.rb
class Sell < ApplicationRecord
  belongs_to :book
  validates :quantity, presence: true
  validates :day, presence: true

  after_create :set_total

  after_create_commit :update_charts


  DAYS = %w[MONDAY TUESDAY WEDNESDAY THURSDAY FRIDAY SATURDAY SUNDAY].freeze

  private
  def set_total
    self.total = self.quantity * self.book.price
    self.save
  end

  def update_charts
    broadcast_replace_to(
      'sells_charts_channel',
      partial: '/dashboard/charts/days/chart',
      locals: { },
      target: 'days_chart')

      broadcast_replace_to(
      'sells_charts_channel',
      partial: '/dashboard/charts/books/chart',
      locals: { book: book},
      target: "book_chart_#{book.id}")

      broadcast_replace_to(
      'sells_charts_channel',
      partial: '/dashboard/charts/revenue/chart',
      locals: { },
      target: 'revenue_chart')
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new book_params
    if @book.save
      respond_to do |format|
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

private
  def book_params
    params.require(:book).permit(:name, :price)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    
  end
end

app/controllers/sells_controller.rb
class SellsController < ApplicationController
  def new 
    @sell = Sell.new
  end

   def create 
    @sell = Sell.new sell_params
    if @sell.save
      respond_to do |format|
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

   private 

   def sell_params
      params.require(:sell).permit(:book_id, :quantity, :day)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def latest_sells id
    array = Array.new

    Book.find(id).sells.each do |sell|
      array.push(sell.quantity)
    end

    array
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/sells_helper.rb
module SellsHelper
  def sells_per_day
    array = Array.new

    Sell::DAYS.each do |day|
      array.push([day, Sell.where(day: day).sum(:quantity)])
    end
    array
  end
  
  def revenue_from_sells
    array = Array.new
    Book.all.each do |book|
    array.push([book.name, book.sells.sum(:total).round(2)])
    end

    array

  end

end

app/views/books/_form.html.erb
<%= turbo_frame_tag 'new_record_component' do %>
    <div class="flex w-full items-center">
        <div data-controller="form">
            <div class="flex w-ful items-center">
                <%= form_with(model: book, class: 'flex w-full items-center gap-2', data: { controller: 'form', action: 'submit->form#resetComponent' }) do |form| %>
                    <% if book.errors.any? %>
                    <% book.errors.each do |error| %>
                        <span class="text-white"><%= error.full_message %></span>
                    <% end %>
                <% end %>
                    
                    <div class="flex gap-2 items-center">
                        <%= form.label :name, class: 'text-xs text-white font-semibold' %>
                        <%= form.text_field :name, class: 'w-full border-2 border-gray-300 p-1 rounded-lg' %>
                    </div>
                    <div class="flex gap-2 items-center">
                        <%= form.label :price, class: 'text-xs text-white font-semibold' %>
                        <%= form.number_field :price, in: 1.0..100.0, step: :any, class: 'w-full border-2 border-gray-300 p-1 rounded-lg' %>
                    </div>
                    <div class="flex items-center justify-end gap-2 ml-5">
                        <%= form.submit 'New Book', class: 'font-semibold p-1 bg-sky-600 text-sm text-white rounded' %>
                        <%= link_to 'Cancel', root_path, class: 'font-semibold p-1 bg-red-600 text-sm text-white rounded' %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
<% end %>

app/views/books/new.html.erb
<%= render 'books/form', {book: @book} %>

app/views/dashboard/charts/books/_books.html.erb
<section class="flex w-full flex-col items-center border">
        <h3 class="text-white font-bold text-lg">Books Sales Report </h3>

        <div  class="flex flex-col" id="books_charts">
                <% Book.all.each do |book| %>
                       
                        <%= render 'dashboard/charts/books/chart', book: book %>
                <% end %>
        </div>
</section>

app/views/dashboard/charts/books/_chart.html.erb
<div data-controller="book" data-book-sells="<%= latest_sells(book.id) %>" book-id="<%= book.id %>"  book-name="<%= book.name %>" class="text-white">
    <canvas id="book_chart_<%= book.id %>"  style="width:100%;max-width:700px" ></canvas>
</div>

app/views/dashboard/charts/days/_chart.html.erb
<div data-controller="days" data-days-sells="<%= sells_per_day %>" id="days_chart">
    <canvas id="daySells"  style="width:100%;max-width:700px"></canvas>

</div>

app/views/dashboard/charts/days/_days.html.erb
<section class="flex w-full flex-col items-center border">
        <h3 class="text-white font-bold text-lg">Sales per day </h3>
        <%= render 'dashboard/charts/days/chart' %>
</section>

app/views/dashboard/charts/revenue/_chart.html.erb
<div data-controller="revenue" data-days-sells="<%= revenue_from_sells %>" id="revenue_chart">
    <canvas id="revenueSells"  style="width:100%;max-width:700px"></canvas>
    <div class="flex flex-col bg-white p-5 rounded mt-10 m-5">
        <h5 class="font-bold text-center my-5 text-xl"> Sells per book </h5>
        <table class="my-5">
            <div class="flex w-full">
                <div class="w-1/3 flex items-center font-semibold boder-2 justify-center text-sm text-center">ID</div>
                <div class="w-1/3 flex items-center font-semibold boder-2 justify-center text-sm text-center">Name</div>
                <div class="w-1/3 flex items-center font-semibold boder-2 justify-center text-sm text-center">Revenue</div>
            </div>
    </div>
    <div class="flex flex-col">
        <% Book.all.each do |book| %>
        <div class="flex mt-2">
            <div class="w-1/3 flex items-center font-semibold boder-2 justify-center text-sm text-center"> <%= book.id %></div>
            <div class="w-1/3 flex items-center font-semibold boder-2 justify-center text-sm text-center"> <%= book.name %></div>
            <div class="w-1/3 flex items-center font-semibold boder-2 justify-center text-sm text-center"> $<%= book.sells.sum(:total).round(2) %></div>
        </div>
    <% end %>
    </div>
    </table>
    <div class="">
        <p class="font-bold text-center my-5 text-xl"> Total: </p>
        <p class="font-bold text-center my-2 text-xl"> $<%= Sell.all.sum(:total) %>
     </div>
  
</div>

app/views/dashboard/charts/revenue/_revenue.html.erb
<section class="flex w-full flex-col items-center border">
        <h3 class="text-white font-bold text-lg">Sales Revenue Report </h3>
        <%= render 'dashboard/charts/revenue/chart' %>
        
</section>

app/views/dashboard/index.html.erb
<%= turbo_stream_from 'books_charts_channel'  %>
<%= turbo_stream_from 'sells_charts_channel'  %>
    <main class="flex flex-col">
        <%= render 'shared/navbar' %>

        <section class="flex flex-col items-center justify-center w-full mt-20 mb-5">
            <div class="flex flex-col items-center">
                <h1 class="text-4xl font-bold text-white my-5">Welcome to the Book Store App</h1>
            </div>
            <div class="flex gap-2 border-2 border-gray-200 w-full h-full">
                <%= render 'dashboard/charts/days/days'%>
                <%= render 'dashboard/charts/books/books'%>
                <%= render 'dashboard/charts/revenue/revenue'%>
            </div>

        </section>
    </main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Book Store" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-black">
    <%= yield %>
  </body>
</html>

app/views/sells/_form.html.erb
<%= turbo_frame_tag 'new_record_component' do %>
    <div class="flex w-ful items-center">
            <%= form_with(model: sell, class: 'flex w-full items-center gap-2', data: { controller: 'form', action: 'submit->form#resetComponent' }) do |form| %>
                <% if sell.errors.any? %>
                    <% sell.errors.each do |error| %>
                        <span class="text-white"><%= error.full_message %></span>
                    <% end %>
                <% end %>
                <div class="flex gap-2 items-center">
                    <%= form.label :book_id, 'Select Book', class: 'text-xs text-white font-semibold' %>
                    <%= form.select(:book_id, Book.all.collect{|book| [book.name, book.id]}, { include_blank: true }, class: 'w-full border-2 border-gray-300 p-1 rounded-lg') %>
                </div>
                <div class="flex gap-2 items-center">
                    <%= form.label :quantity, class: 'text-xs text-white font-semibold' %>
                    <%= form.number_field :quantity, class: 'w-full border-2 border-gray-300 p-1 rounded-lg' %>
                </div>
                <div class="flex gap-2 items-center">
                    <%= form.label :day, 'Select Day', class: 'text-xs text-white font-semibold' %>
                    <%= form.select( :day, Sell::DAYS.map{|day| [day.humanize, day]}, {include_blank: true }, class: 'w-full border-2 border-gray-300 p-1 rounded-lg')  %>
                </div>
              
                <div class="flex items-center justify-end gap-2 ml-5">
                    <%= form.submit 'New Sell', class: 'font-semibold p-1 bg-sky-600 text-sm text-white rounded' %>
                    <%= link_to 'Cancel', root_path, class: 'font-semibold p-1 bg-red-600 text-sm text-white rounded' %>
                </div>
            <% end %>
        </div>
<% end %>

app/views/sells/_text.html.erb
<div class="flex w-ful items-center">
            <%= form_with(model: sell, class: 'flex w-full items-center gap-2', data: { controller: 'form', action: 'submit->form#resetComponent' }) do |form| %>
                <% if sell.errors.any? %>
                    <% sell.errors.each do |error| %>
                        <span class="text-white"><%= error.full_message %></span>
                    <% end %>
                <% end %>
                <div class="flex gap-2 items-center">
                    <%= form.label :book_id, 'Select Book', class: 'text-xs text-white font-semibold' %>
                    <%= form.select(:book_id, Book.all.collect{|book| [book.name, book.id]}, { include_blank: true }, class: 'w-full border-2 border-gray-300 p-1 rounded-lg') %>
                </div>
                <div class="flex gap-2 items-center">
                    <%= form.label :quantity, class: 'text-xs text-white font-semibold' %>
                    <%= form.number_field :quantity, class: 'w-full border-2 border-gray-300 p-1 rounded-lg' %>
                </div>
              
                <div class="flex items-center justify-end gap-2 ml-5">
                    <%= form.submit 'New Book', class: 'font-semibold p-1 bg-sky-600 text-sm text-white rounded' %>
                    <%= link_to 'Cancel', root_path, class: 'font-semibold p-1 bg-red-600 text-sm text-white rounded' %>
                </div>
            <% end %>
        </div>

app/views/sells/new.html.erb
<%= render 'form', sell: @sell %>

app/views/shared/_navbar.html.erb
<nav class="w-full flex bg-black items-center p-5 justify-between fixed">
    <div class="flex gap-5 items-center">
        <%= image_tag('book.png', class: 'w-12') %>
        <h3 class="font-bold text-lg text-white">The Book Store App</h3>
    </div>

    <div class="flex items-center justify-between">
        <%= turbo_frame_tag 'new_record_component', class: 'flex gap-2' do %>
            <%= link_to new_sell_path, id: 'sell_link', class: 'text-white font-semibold text-sm text-center bg-green-700 text-white my-2' do %> 
                Add Sell 
            <% end %>
        

            <%= link_to new_book_path, id: 'book_link', class: 'text-white font-semibold text-sm text-center bg-sky-700 text-white my-2' do %> 
            Add new Book
            <% end %>
        <% end %>
    </div>
</nav>